/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginprojeto;
import cadastrar.MysqlConnect;
import cadastrar.cadastro;
import controle.Usuario;
import controle.UsuarioDaoArquivo;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import programaprincipal.programaPrincipal;
/**
 *
 * @author Felipe Gomes
 */
public class Login extends javax.swing.JFrame {
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    private UsuarioDaoArquivo dao;
    /**
     * Creates new form Login
     */
    public Login() {
        try{
            dao = new UsuarioDaoArquivo();
        }catch(IOException ex){
            JOptionPane.showMessageDialog(null, "Falha","Mensagem de erro", JOptionPane.ERROR_MESSAGE);
        }
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoFechar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoLogin = new javax.swing.JTextField();
        campoSenha = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        campoEntrar = new javax.swing.JButton();
        campoCadastro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(129, 209, 139));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Line Chart_70px.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("AjudaFinança");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        campoFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Multiply_32px.png"))); // NOI18N
        campoFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        campoFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoFecharMouseClicked(evt);
            }
        });
        jPanel1.add(campoFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 100));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(98, 200, 115));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 240, 10));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 240, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(98, 200, 115));
        jLabel3.setText("Login");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(98, 200, 115));
        jLabel4.setText("Senha");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        campoLogin.setBorder(null);
        jPanel2.add(campoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 240, 23));

        campoSenha.setBorder(null);
        campoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSenhaActionPerformed(evt);
            }
        });
        jPanel2.add(campoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 193, 230, 23));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_32px.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 55, -1, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Key_32px.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, 50));

        campoEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Login_50px.png"))); // NOI18N
        campoEntrar.setBorder(null);
        campoEntrar.setContentAreaFilled(false);
        campoEntrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LoginClicked_50px.png"))); // NOI18N
        campoEntrar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LoginClicked_50px.png"))); // NOI18N
        campoEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoEntrarMouseClicked(evt);
            }
        });
        campoEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEntrarActionPerformed(evt);
            }
        });
        jPanel2.add(campoEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        campoCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Plus Math_50px.png"))); // NOI18N
        campoCadastro.setBorderPainted(false);
        campoCadastro.setContentAreaFilled(false);
        campoCadastro.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Plus MathClicked_50px.png"))); // NOI18N
        campoCadastro.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Plus MathClicked_50px.png"))); // NOI18N
        campoCadastro.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Plus MathClicked_50px.png"))); // NOI18N
        campoCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoCadastroMouseClicked(evt);
            }
        });
        campoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCadastroActionPerformed(evt);
            }
        });
        jPanel2.add(campoCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 50, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 310, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSenhaActionPerformed

    private void campoFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoFecharMouseClicked
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja sair do programa?");
        if (opcao == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_campoFecharMouseClicked

    private void campoEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoEntrarMouseClicked
        programaPrincipal principal = new programaPrincipal();
        System.out.println("Entrou");
        try{
            if(dao.buscar(campoLogin.getText(), campoSenha.getText())){
                JOptionPane.showMessageDialog(null, "Bem vindo "+campoLogin.getText());
                principal.setVisible(true);
                this.setVisible(false);
            }else{
                JOptionPane.showMessageDialog(null, "Login não efetuado! Usuário ou senha incorretos.", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }catch(IOException | ClassNotFoundException ex){
            JOptionPane.showMessageDialog(null, "Erro ao logar!");
        }
        /*
        conn = MysqlConnect.ConnectDB();
        
        String Sql = "SELECT * FROM login WHERE nome = ? and senha = ?";
        try{
            pst = conn.prepareStatement(Sql);
            pst.setString(1, campoLogin.getText());
            pst.setString(2, campoSenha.getText());
            rs = pst.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "WELCOME USER");
                programaPrincipal principal = new programaPrincipal();
                principal.setVisible(true);
                this.dispose();
                
            }else{
                JOptionPane.showMessageDialog(null, "INVALID USERNAME OR PASSWORD!", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }*/
        
    }//GEN-LAST:event_campoEntrarMouseClicked

    private void campoEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEntrarActionPerformed
        
    }//GEN-LAST:event_campoEntrarActionPerformed

    private void campoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCadastroActionPerformed

    private void campoCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoCadastroMouseClicked
        cadastro Cadastro = new cadastro();
        Cadastro.setVisible(true);      
    }//GEN-LAST:event_campoCadastroMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton campoCadastro;
    private javax.swing.JButton campoEntrar;
    private javax.swing.JLabel campoFechar;
    private javax.swing.JTextField campoLogin;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

}
